version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    restart: always
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080 

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 9090:8080
