version: '3.1'

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: boostar_deck
    ports:
      - 5432:5432
      
  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 9090:8080