# Generated by Django 3.1.3 on 2020-11-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of flashcard')),
                ('reverse', models.CharField(max_length=1200, verbose_name='Revers of card')),
                ('averse', models.CharField(max_length=1200, verbose_name='Avers of card')),
                ('tip', models.CharField(max_length=100, verbose_name='Tip for flash card')),
            ],
            options={
                'verbose_name': 'Flash Card',
                'verbose_name_plural': 'Flash Cards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of levels')),
                ('repeat_frequancy', models.IntegerField(verbose_name='time of frequency')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeckFlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_answers', models.IntegerField(verbose_name='good answers')),
                ('bad_answers', models.IntegerField(verbose_name='bad answers')),
                ('flashCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flashcard')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level')),
            ],
            options={
                'verbose_name': 'DeckFlash',
                'verbose_name_plural': 'DeckFlashes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of deck')),
                ('description', models.CharField(max_length=1200, verbose_name='Description of deck')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('deckFlashCard', models.ManyToManyField(to='core.DeckFlashCard')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['name'],
            },
        ),
    ]
