# Generated by Django 3.1.3 on 2020-11-21 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of deck')),
                ('description', models.CharField(max_length=1200, verbose_name='Description of deck')),
                ('tag', models.CharField(max_length=50, verbose_name='tag')),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeckFlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_answers', models.IntegerField(default=0, verbose_name='good answers')),
                ('bad_answers', models.IntegerField(default=0, verbose_name='bad answers')),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deck')),
            ],
            options={
                'verbose_name': 'DeckFlashCard',
                'verbose_name_plural': 'DeckFlashCards',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of levels')),
                ('repeat_frequancy', models.IntegerField(verbose_name='time of frequency')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of flashcard')),
                ('reverse', models.CharField(max_length=1200, verbose_name='Revers of card')),
                ('averse', models.CharField(max_length=1200, verbose_name='Avers of card')),
                ('tip', models.CharField(max_length=100, verbose_name='Tip for flash card')),
                ('deck', models.ManyToManyField(related_name='deck', through='core.DeckFlashCard', to='core.Deck')),
            ],
            options={
                'verbose_name': 'Flash Card',
                'verbose_name_plural': 'Flash Cards',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deckflashcard',
            name='flashCard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flashcard'),
        ),
        migrations.AddField(
            model_name='deckflashcard',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level'),
        ),
        migrations.AddField(
            model_name='deck',
            name='flashCard',
            field=models.ManyToManyField(related_name='flashCard', through='core.DeckFlashCard', to='core.FlashCard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL),
        ),
    ]
