# Generated by Django 3.1.3 on 2020-11-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deckFlashCard',
        ),
        migrations.AddField(
            model_name='deck',
            name='flashCard',
            field=models.ManyToManyField(related_name='flashCard', through='core.DeckFlashCard', to='core.FlashCard'),
        ),
        migrations.AddField(
            model_name='deckflashcard',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deck'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ManyToManyField(related_name='deck', through='core.DeckFlashCard', to='core.Deck'),
        ),
    ]
