# Generated by Django 3.1.4 on 2021-04-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flashcard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckflashcard',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.deck'),
        ),
        migrations.AlterField(
            model_name='deckflashcard',
            name='flashcard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.flashcard'),
        ),
    ]
