name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tox
        run: |
          pip install tox

      - name: Cache requirements
        uses: actions/cache@v2
        id: cache-tox
        with:
          path: ${{ github.workspace }}/.tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/Pipfile.lock') }}${{hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: create .env
        run: |
          cp .env.example .env

      - name: Run tox test
        run: |
          tox -e test

   lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tox
        run: |
          pip install tox

      - name: Cache requirements
        uses: actions/cache@v2
        id: cache-tox
        with:
          path: ${{ github.workspace }}/.tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/Pipfile.lock') }}${{hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: create .env
        run: |
          cp .env.example .env

      - name: Run tox lint
        run: |
          tox -e lint

   format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tox
        run: |
          pip install tox

      - name: Cache requirements
        uses: actions/cache@v2
        id: cache-tox
        with:
          path: ${{ github.workspace }}/.tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/Pipfile.lock') }}${{hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: create .env
        run: |
          cp .env.example .env

      - name: Run tox format
        run: |
          tox -e format