name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv, libpq, and pandoc
        run: |
          sudo apt-get install libpq-dev -y
          pip install pipenv

      - name: Cache requirements
        uses: actions/cache@v2
        id: cache-pipenv
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-virtualenvs-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-virtualenvs-

      - name: Install dependency
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Pylint check
        run: |
          apps_names=$(find . -maxdepth 1  -name "*" -type d -not -name '.*')  
          for i in $apps_names; do
          pylint $i
          done

      - name: Black reformat check
        run: |
          black --check . --exclude 'migrations|manage.py'

      - name: Run django test
        run: |
          pipenv run py.test
